version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '5432:3306'
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./storage/db:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    container_name: sales-api
    build:
      context: ./
    image: sales-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    links:
      - db
volumes:
  db:
    driver: local