version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '5432:3306'
    volumes:
      - ./sql/TestTaskDBScript.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: sales-api
    build:
      context: ./
    image: sales-api
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db
volumes:
  db:
    driver: local